general:
  debug: true
  cron: '*/15 * * * *'
darksky:
  key: DARKSKY_KEY
  units: si
  language: en
  latitude: DARKSKY_LATITUDE
  longitude: DARKSKY_LONGITUDE  
influxdb:
  host: INFLUXDB_HOST
  port: INFLUXDB_PORT
  database: INFLUXDB_DATABASE
  username: INFLUXDB_USERNAME
  password: INFLUXDB_PASSWORD
